### PR TITLE
Create send2telegraph.sh

### PR DESCRIPTION
**Pull request by JorgePe**
This is the bash script I use on my Ubuntu laptop to send text from console to the ev3dev-telegraph.
You can  also redirect a whole file to it, great for recording nice promo videos.

### CODE REVIEW

**Comment by dlech** [comment]
Nice. Thanks!

**Comment by JorgePe** [comment]
I also have the receiving script but not good, I'm having problems with displaying A, J and K, I think because of the way bash 'read' handles escaped characters.
A = 0 is the null char,
J = 9 is NULL + TAB and is shown also as 'A' 
K = 10 is NULL + NEW LINE and is shown as 'AA'

**Comment by dlech** [comment]
If you want to post it, I have take a look at it.

**Comment by JorgePe** [comment]
Will do.

I'm not a fan of bash but since the first script was easy I started this
second one... not easy now.
The coding you choose (0x00..0x19) was totally by chance or there is a
better reason?
I ask because I was also trying to receive messages on my Android MQTT
[generic] apps and only one of them has an option to treat values as
binary, all others ignore the received value because is not in the ASCII
range.

**Comment by dlech** [comment]
> The coding you choose (0x00..0x19) was totally by chance or there is a better reason?

This is what is used in the EV3-G program written by Jason Alleman. This way, an ev3dev telegraph can communicate with an EV3-G telegraph via bluetooth (bluetooth comms are not implemented in ev3dev yet).

However, this repo is a fork, so we can change whatever we want. It certainly would simplify things to use ASCII values instead of translating.

**Comment by JorgePe** [comment]
For the original purpose, 0x00..0x19 is fine. And keeping compatibility
with EV3-G based telegraphs would be great.

The send2telegraph goal was to send always the same file so I could record
a video for our LUG next event. For that purpose, it was great.
For more complex scenarios, a decent programming language would probably
handle 0x00 and 0x0A better than bash [and me] so I see no reason to change
the coding.

**Comment by JorgePe** [comment]
Found the reason, 'mosquitto_sub' adds an EOL ('\n') to each message it
prints and 'read' by default removes all spaces, EOL and TAB. That
converted all 'J' in NUL ('A') and all 'K' in 2xNUL.

**Comment by JorgePe** [comment]
BTW I'm using jorgepe, are you using dlech like you said on facebook?

**Comment by dlech** [comment]
I think so. It is not turned on right now.

**Pull request merged**
